### ISSUE TITLE
Coins - individual mob drop support

### ISSUE THREAD

**Issue by madtomic** [JustEli/Coins#3]
Can you add mob drop settings in the config for Coins. Thank you

config.yml 
https://pastebin.com/70bfGt6q

**Comment by JustEli** [comment]
From the Spigot info page:


It's possible to make mobs drop different amount of money.
The Ender Dragon drops 64 coins, and players drop 3 coins by default.
You can change this. If you want endermen - for example - to drop 2 coins, add it:

```yaml
mobMultiplier:
  ENDER_DRAGON: 64
  PLAYER: 3
  ENDERMAN: 2
```
