### ISSUE TITLE
Batch Withdrawal

### ISSUE THREAD

**Issue by joex92** [JustEli/Coins#33]
Sometimes when using _item based_ trading plugins (like [Shopkeepers](https://github.com/Shopkeepers/Shopkeepers))  its needed to have the currency item as separate values, for example:
I'm trading some item for $100, and the trading plugin is using 10 currency items of $10 of value each, so if I need to get that trade, I have to do `/withdraw 10` x10 times, and this is a "little example", Imagine if it was 100 currency items of $1 value each...

so my request is something like this:

- either add to the `/withdraw` command a second argument like this: `/withdraw [value] [quantity]` given quantity 1 by default...

- or add a new command: `/batchwithdraw [value] [quantity]`

for now I'm using a plugin called [MyCommand](https://dev.bukkit.org/projects/mycommand/pages/configuration-and-example) which lets you create your own commands, so I did it like this:
```yml
batch_withdraw:
  command: /bwithdraw
  type: RUN_COMMAND_TASK
  runcmd:
  - '/withdraw $arg1'
  tab_completer:
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 192
  - 256
  - 320
  - 640
  error-message: '&cHELP: &e/bwithdraw [$] [#]'
  required_args: 2
  require_all_args: true
  task_run_immediately: true
  task_repeat_every_sec: -1
  task_run_n_times: $arg2
  task_run_when_offline: true
  task_show_debug: false
  register: true
```
the only issue is that each time `/withdraw` is run by this command, it spams the chat with the message about each withdrawal... 

this is in my case, but what about other people trying to do something like this and don't want to add another plugin to be able to do it? that's my request...
