### ISSUE TITLE
Multiple money drop types and control over which mobs drop them

### ISSUE THREAD

**Issue by iielijah** [JustEli/Coins#38]
Hello,

**Is your feature request related to a problem? Please describe.**
issue is i like this plugin but it would be nice to have something more for my liking for what im trying to accomplish.

**Describe the solution you'd like**
So my server is based on the Nexon game, "MapleStory". How this relates is that on maplestory you get different types of cash varying in amount you receive to your balance. Mesos = lowest tier, Maple Coins = medium tier, stacks of dollars = high tier, and mesos bags = highest. Trying to replicate that on my server in where lower tier mobs drop mesos, medium tier mobs drop maplecoins, so on and so forth. I preferably would like to control which mob gets which type of currency and would also like custommodeldata support on all level of tiers so i customize them to look as such in this photo: 
![16158](https://user-images.githubusercontent.com/65664977/110230303-dd836e00-7ec4-11eb-9093-449f3b213a1e.png)
another idea would be to randomize the drops but still be able to customize the drop types generally speaking in terms of what are available.

**Describe alternatives you've considered**
no comment.

**Additional context**
no comment.

Regards,
Elijah

**Comment by JustEli** [comment]
exactly this is something in the making at the moment, it requires a total rewrite of the plugin, so it'll be in 2.0, and i expect to be done with it in about 6 months

**Comment by iielijah** [comment]
Ah well that is exciting news. More than happy to be patient for something like that. Thanks!

**Comment by iielijah** [comment]
Sorry just curious if this sorta feature will be implemented?
![mobcash](https://user-images.githubusercontent.com/65664977/110510757-60204f00-80b8-11eb-8cfc-da69b229c858.PNG)
It's from this plugin: https://www.spigotmc.org/resources/mobcash.25057/
Where you can choose constant or varied amounts of drops from specific mobs.. I'm sorry i know you're working hard just thought i'd suggest that.

**Comment by iielijah** [comment]
oh im so dumb i saw it in the configs

**Comment by JustEli** [comment]
it's going to be something like this, or at least, that's what i have written down so far for my idea:

```yaml
# Define any kind of coin.
# Check out: https://github.com/JustEli/Coins/wiki/defining-coins
coins:
  # Name of this configured coin, later used in other parts of the config.
  BLOCK:
    item: GOLD_BLOCK      # material of this coin
    worth: [10.0, 15.0]   # the range to determine random worth
    glow: true            # will give an enchanted effect
    chance: 0.1           # default chance, overridable in 'drops'
  INGOT:
    item: GOLD_INGOT
    worth: [5.0, 9.0]
    chance: 0.3
```


```yaml
# Tell the plugin when and what coins to drop.
# Check out: https://github.com/JustEli/Coins/wiki/defining-drops
drops:
  # The name/identifier of this configured drop. Can be anything.
  playerKill:
    # Whether this should be enabled or not. Ignored on startup if false.
    enabled: false
    # The listeners/events to listen to for this drop.
    # For this drop, it will listen to punch kills and projectile kills.
    listeners: [KILL_ENTITY, KILL_ENTITY_PROJECTILE]
    # Select what should be allowed to drop coins when event is triggered.
    selectors:
      entities: [PLAYER]      # players will drop coins if killed by another player
      preventAlts: true       # but prevent if player was killed by an alt
  hostileKill:
    enabled: true
    listeners: [KILL_ENTITY, KILL_ENTITY_PROJECTILE]
    selectors:
      entities: [HOSTILE]     # all hostile mobs will drop a coin with this event
      spawners: false         # but not if they're from spawners
      slimeSplit: false       # and exclude slimes that were spawned by split
  passiveKill:
    enabled: false
    listeners: [KILL_ENTITY, KILL_ENTITY_PROJECTILE]
    selectors:
      entities: [PASSIVE]
      spawners: false
    chance:
      INGOT: 0.2              # override the default drop chance for INGOT
      NUGGET: 0.4             # and also do so for NUGGET
  entityDeath:
    enabled: false
    # This listener is for any death, also when not killed by a player.
    listeners: [ENTITY_DEATH]
    selectors:
      entities: [HOSTILE, PASSIVE]
      spawners: false
      slimeSplit: false
  mineValuableOre:
    enabled: false
    listeners: [BREAK_BLOCK]
    selectors:
      materials:              # materials in this event that are selected
      - EMERALD_ORE
      - DIAMOND_ORE
      - LAPIS_LAZULI_ORE
    chance:
      BLOCK: 0.2
```
